name: n8n Release Monitor

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths: 
      - '.github/workflows/n8n-monitor.yml'
      - 'n8n_monitor.py'

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch full history to enable git operations
        fetch-depth: 0

    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Run n8n release monitor
      run: |
        uv run n8n_monitor.py --monitor

    - name: Check for changes in data files
      id: git-check
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "n8n Release Monitor"
        
        # Check if there are any changes to commit
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected in data files"
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git add data/
        git commit -m "📦 Update n8n release data - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push

    - name: Upload artifacts (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: n8n-release-data
        path: data/
        retention-days: 30